apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
  labels:
    project: nginx
    environment: testing
spec:
  replicas: 4
  selector:
    project: nginx
  template:
    metadata:
      name: nginx
      labels:
        project: nginx
        enviorenment: testing
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
