apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels: 
    project: frontend
    environment: testing
spec:
  # this replicas vale is default
  # modify it according to uour case
  replicas: 2
  selector:
    matchLabels:
      app: nginx
    matchExpressions:
      - {key: environment, operator: In, values: [testing]}
  template:
    metadata:
      labels:
        app: nginx
        environment: testing
    spec:
      containers:
      - name: nginx
        image: dahwild/kubernetes-test
        ports:
        - containerPort: 80
