apiVersion: v1
kind: Pod
metadata: 
  name: nginx
  labels:
    k8s-app: web
    enviroment: testing
  annotations:
    note: "this site is under construction"
    misDatos:
      nombre:Wilder
      apellido:David
spec: 
  containers:
  - name: nginx
    image: nginx:1.7.9
    ports:
    - containerPort: 80
