apiVersion: v1
kind: Pod
metadata:
  name: nginx-limits
spec:
  restartPolicy: Never
  containers:
    - name: web
      image: nginx
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
