apiVersion: v1
kind: Pod
metadata:
  name: nginx-cm
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        # Define the environment variable
        - name: ENVIRONMENT_TEST
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: test-cm
              # Specify the key associated with the value
              key: variable1
         
        - name: DATABASE_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: test-cm-2
              key: variable2
              
